---
- name: Add SSH banner
  copy:
    src: "{{ sshd_banner }}"
    dest: /etc/ssh/banner
    owner: root
    group: root
    mode: 0644
  notify:
    - sshd

- name: Configure sshd
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - sshd

- name: Create _sshd_keyuser
  user:
    name: _sshd_keyuser
    state: present
    system: yes
    createhome: no
  when: sshd_AuthorizedKeysCommand is defined
